name: Retrain Model

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  train:

    runs-on: ubuntu-latest

    steps:

      # ==========================
      # CHECKOUT REPOSITORY
      # ==========================

      - name: Checkout Repository
        uses: actions/checkout@v4

      # ==========================
      # SETUP PYTHON
      # ==========================

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # ==========================
      # INSTALL DEPENDENCIES
      # ==========================

      - name: Install Dependencies
        run: |
          pip install mlflow
          pip install pandas
          pip install scikit-learn
          pip install matplotlib

      # ==========================
      # RUN TRAINING
      # ==========================

      - name: Run Training
        run: |
              mlflow run MLProject --env-manager local

      # ==========================
      # SAVE ARTIFACT
      # ==========================

      - name: Upload MLflow Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: trained-model
          path: mlruns

      # ==========================
      # DEBUG SECRET
      # ==========================

      - name: Check Username Secret
        run: |
          echo "USERNAME=${{ secrets.DOCKER_HUB_USERNAME }}"

      # ==========================
      # LOGIN DOCKER HUB
      # ==========================

      - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      # ==========================
      # BUILD DOCKER IMAGE
      # ==========================
      - name: Build Docker Image with MLflow
        run: |
          mlflow models build-docker \
            -m MLProject/model \
            -n diannazira/telco-churn-model
      
      # ==========================
      # PUSH DOCKER IMAGE
      # ==========================

      - name: Push Docker Image
        run: |
          docker push diannazira/telco-churn-model:latest